# global 
woocommerce_enable="TRUE"
woocommerce_hpos="TRUE"
notification_email="example@email.com"
alert_email="example@email.com"
xmllint="/usr/bin/xmllint"
php="/usr/bin/php82"
galera_restart="FALSE"
gform_entries="TRUE"

wprocket="FALSE"
flyingpress="FALSE"

# staging
staging_db_name="staging_db"
staging_db_user="staging_user"
staging_db_password="staging_pass"
staging_db_host="localhost"
staging_host="staging.example.com"
staging_user="root"
source_dir="/var/www/staging.example.com/public_html"
wp_cli_staging="/usr/local/bin/wp"

# production
prod_db_name="prod_db"
prod_db_user="prod_user"
prod_db_password="prod_pass"
prod_db_host="localhost"
prod_db_backup_dir="/home/push-backups"
destination_dir="/var/www/example.com/public_html"
destination_user="root"
destination_host="0.0.0.0"
wp_cli_prod="/usr/bin/php82 -d error_reporting=E_ERROR /usr/local/bin/wp"

